# Generated by Django 3.2.7 on 2021-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
