# Generated by Django 3.2.7 on 2021-11-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20211107_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.IntegerField(default=0),
        ),
    ]
