# Generated by Django 3.2.7 on 2021-11-07 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20211107_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 21, 38, 7, 226147, tzinfo=utc), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(default='NO_DESCRIPTION'),
        ),
    ]
