# Generated by Django 3.2.7 on 2021-11-07 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20211107_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 21, 38, 48, 679162, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
