# Generated by Django 3.2.7 on 2021-11-07 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 22, 22, 3, 944084, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
