# Generated by Django 3.2.7 on 2021-11-07 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20211107_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='aircon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='shared_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 22, 29, 58, 381955, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
