# Generated by Django 3.2.7 on 2021-11-08 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20211107_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 2, 58, 7, 494816, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
