# Generated by Django 3.2.7 on 2021-11-08 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 3, 16, 129708, tzinfo=utc), verbose_name='date posted'),
        ),
    ]
