# Generated by Django 3.2.7 on 2021-11-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20211101_1554'),
        ('listings', '0014_auto_20211108_0303'),
    ]

    operations = [
    ]
