# Generated by Django 3.2.7 on 2021-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20211108_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='link',
            field=models.URLField(default='NO_LINK', max_length=100),
        ),
    ]
