# Generated by Django 3.2.7 on 2021-11-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_listing_review_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='lon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
