# Generated by Django 3.2.8 on 2021-11-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20211111_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
