# Generated by Django 3.2.7 on 2021-10-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
